runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"

handlers:
- url: /
  script: run.app

- url: /home
  script: run.app
  
- url: /search
  script: run.app